### ISSUE TITLE
Comparison to `carnix`

### ISSUE THREAD

**Issue by Profpatsch** [kolloch/crate2nix#13] opened 2019-07-22 14:49 UTC
`carnix` seems to be the standard tool for transforming rust packages to nix derivations. What’s the differences in features?

I would vastly prefer `crate2nix`, simply because `carnix` has no bit of documentation, no changelog, and does not integrate with nixpkgs best practices (e.g. they decided to use Pijul instead of git(hub) like the rest of the ecosystem).

Examples oh what I’m looking for are: 
* how well does `crate2nix` support crate `features`, compared to `carnix`
* status of overriding packages

Existing features / missing features should always compare to `carnix`.

**Comment by kolloch** [comment] 2019-07-23 07:40
The problem is that `carnix` - as you pointed out - has no real documentation (that I know of) and is a moving target. Features used to work somewhat, then they stopped working (maybe they work again?).

If you would give it a go and send patches that add feature comparisons to the features, I trust you and gladly accept them.

**Comment by Profpatsch** [comment] 2019-07-23 08:54
> If you would give it a go and send patches that add feature comparisons to the features, I trust you and gladly accept them.

My problem is that I have never used carnix, so I have no frame of reference :)

**Comment by kolloch** [comment] 2019-10-11 09:41
If someone would write a comparison, I'd appreciate it! I will not put time into this myself at the moment.

**Comment by kolloch** [comment] 2020-02-19 20:02
@P-E-Meunier commented in https://github.com/kolloch/crate2nix/issues/99 that he would prefer if the ecosystem went ahead using `crate2nix` instead of `carnix` -- he even offered to donate the name.

So I'd close this.

**Closed by kolloch** 2020-02-19 20:02 UTC
Labels: help wanted
